### ISSUE TITLE
Goes haywire on both LD2410B and LD2410C

### ISSUE THREAD

**Issue by andorardo** [albertnis/ld2410-configurator#14] opened 2024-11-13 00:30 UTC
I have both an LD2410B and C, connected via USB UART adapter to two Macs running Chrome.

On both laptops, with both devices, I get this behavior:

![image](https://github.com/user-attachments/assets/34714738-392f-4d60-8266-1b9e6741c219)

It flashed intensely, as the numbers switch quickly between small (hundred) and large (tens of thousands).

What might be going on? It's almost like some endianness is being misinterpreted?

**Comment by albertnis** [comment] 2024-11-16 02:14
Thanks for the report. That's seriously strange. I'm unable to reproduce this on a LD2410C. I wonder if there is a new protocol version, firmware, variant or something like that. 

- Could you please send an excerpt from the serial console? I'm particularly interested in how the device replies to the payload sent by the configurator when you click "Reload all".
- When you click "Reload all", does any information ever get populated in the "Firmware version" and "Protocol version" fields up top?
- Roughly when did you purchase each of your sensors?

**Comment by andorardo** [comment] 2024-11-19 15:59
A few weeks ago, I bought one "LD2410B kit" and one "LD2410C kit" from https://www.aliexpress.us/item/3256805945328831.html 

#### LD2410C

Here's an excerpt form the serial console for the LD2410C: https://gist.github.com/andorardo/ae19b1756d24d2e8902be451986621d1

I tried repeatedly pressing "Reload all", but unfortunately nothing changed.

#### LD2410B

Same phenomenon when trying to connect at 256000.

I was able to connect to the LD2410B via BT via the iPad app, and configured the serial port to a slower speed 230400. Now the details show up: Firmware version 2.68.36074916 Protocol version 1.

Here is the serial console from the *slow* LD2410B: https://gist.github.com/andorardo/7a15873084cc371bfcc76c42f14f1d54 -- Is that helpful?

#### Serial adapter

The kit comes with a CH340, which is what I've been using. I don't know if that makes any difference.

PS: I ordered a FT232 in (the unlikely) case this has something to do with the UART adapter.

**Comment by andorardo** [comment] 2024-11-20 02:41
UPDATE: The FT232 arrived this afternoon, sooner than I expected. The LD2410C now works. 👍  Also: Firmware version 2.68.36074916 Protocol version 1

I'm glad that's sorted. :) Needless to say, I'm rather disappointed in the UART that came with the kit.  :(

**Comment by albertnis** [comment] 2024-11-20 02:47
Thanks for the additional info, and the confirmation that things are working now with a new serial-to-USB adapter. I'll close the issue but please re-open it if you think there's something broken in the configurator which contributes to the haywire behaviour you saw previously.

Also keep an eye on #13 which implements Bluetooth in the configurator. I finally got around to reviewing and testing the PR recently and it's a great alternative to using Serial over UART and USB.

**Closed as completed by albertnis** 2024-11-20 02:47 UTC
